version: '3.8'

services:
  ml-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PORT=5000
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./models:/app/models 